// See LICENSE for license details.

package craft

import chisel3._
import chisel3.experimental._

class ADCIO extends Bundle {
  val ADCBIAS     = Analog(1.W)
  val ADCINP      = Analog(1.W)
  val ADCINM      = Analog(1.W)
  val ADCCLKP     = Analog(1.W)
  val ADCCLKM     = Analog(1.W)
  val extclk0     = Input(Bool())
  val extclk1     = Input(Bool())
  val extclk2     = Input(Bool())
  val extclk3     = Input(Bool())
  val extclk4     = Input(Bool())
  val extclk5     = Input(Bool())
  val extclk6     = Input(Bool())
  val extclk7     = Input(Bool())
  val osp0        = Input(UInt(8.W))
  val osp1        = Input(UInt(8.W))
  val osp2        = Input(UInt(8.W))
  val osp3        = Input(UInt(8.W))
  val osp4        = Input(UInt(8.W))
  val osp5        = Input(UInt(8.W))
  val osp6        = Input(UInt(8.W))
  val osp7        = Input(UInt(8.W))
  val osm0        = Input(UInt(8.W))
  val osm1        = Input(UInt(8.W))
  val osm2        = Input(UInt(8.W))
  val osm3        = Input(UInt(8.W))
  val osm4        = Input(UInt(8.W))
  val osm5        = Input(UInt(8.W))
  val osm6        = Input(UInt(8.W))
  val osm7        = Input(UInt(8.W))
  val asclkd0     = Input(UInt(4.W))
  val asclkd1     = Input(UInt(4.W))
  val asclkd2     = Input(UInt(4.W))
  val asclkd3     = Input(UInt(4.W))
  val asclkd4     = Input(UInt(4.W))
  val asclkd5     = Input(UInt(4.W))
  val asclkd6     = Input(UInt(4.W))
  val asclkd7     = Input(UInt(4.W))
  val extsel_clk0 = Input(Bool())
  val extsel_clk1 = Input(Bool())
  val extsel_clk2 = Input(Bool())
  val extsel_clk3 = Input(Bool())
  val extsel_clk4 = Input(Bool())
  val extsel_clk5 = Input(Bool())
  val extsel_clk6 = Input(Bool())
  val extsel_clk7 = Input(Bool())
  val vref00      = Input(UInt(8.W))
  val vref01      = Input(UInt(8.W))
  val vref02      = Input(UInt(8.W))
  val vref03      = Input(UInt(8.W))
  val vref04      = Input(UInt(8.W))
  val vref05      = Input(UInt(8.W))
  val vref06      = Input(UInt(8.W))
  val vref07      = Input(UInt(8.W))
  val vref10      = Input(UInt(8.W))
  val vref11      = Input(UInt(8.W))
  val vref12      = Input(UInt(8.W))
  val vref13      = Input(UInt(8.W))
  val vref14      = Input(UInt(8.W))
  val vref15      = Input(UInt(8.W))
  val vref16      = Input(UInt(8.W))
  val vref17      = Input(UInt(8.W))
  val vref20      = Input(UInt(8.W))
  val vref21      = Input(UInt(8.W))
  val vref22      = Input(UInt(8.W))
  val vref23      = Input(UInt(8.W))
  val vref24      = Input(UInt(8.W))
  val vref25      = Input(UInt(8.W))
  val vref26      = Input(UInt(8.W))
  val vref27      = Input(UInt(8.W))
  val iref0       = Input(UInt(8.W))
  val iref1       = Input(UInt(8.W))
  val iref2       = Input(UInt(8.W))
  val clkgcal0    = Input(UInt(8.W))
  val clkgcal1    = Input(UInt(8.W))
  val clkgcal2    = Input(UInt(8.W))
  val clkgcal3    = Input(UInt(8.W))
  val clkgcal4    = Input(UInt(8.W))
  val clkgcal5    = Input(UInt(8.W))
  val clkgcal6    = Input(UInt(8.W))
  val clkgcal7    = Input(UInt(8.W))
  val clkgbias    = Input(UInt(8.W))
  val adcout0     = Output(UInt(9.W))
  val adcout1     = Output(UInt(9.W))
  val adcout2     = Output(UInt(9.W))
  val adcout3     = Output(UInt(9.W))
  val adcout4     = Output(UInt(9.W))
  val adcout5     = Output(UInt(9.W))
  val adcout6     = Output(UInt(9.W))
  val adcout7     = Output(UInt(9.W))
  val clkout_des      = Output(Clock())
  val clkrst      = Input(Bool())
}

class TISARADC extends BlackBox {
  val io = IO(new ADCIO)
}

class DeserIO extends Bundle {
  val in           = Input(Vec(8, UInt(9.W)))
  val out          = Output(Vec(32, UInt(9.W)))
  val clk          = Input(Clock())
  val rst          = Input(Bool())
  // clock that follows data to fifo
  val clkout_data = Output(Clock())
  // clock that goes to rest of the dsp chain
  val clkout_dsp = Output(Clock())
  // set the phase during reset
  val phi_init = Input(UInt(2.W))
}

class des72to288 extends BlackBox {
  val io = IO(new DeserIO)
}
